apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sms-prod

resources:
  - ../../base
  - sealed-secret.yaml
  - switchover.yaml

# newTag is rewritten by .github/workflows/deploy.yml on every push to main.
images:
  - name: ghcr.io/benmcd23/sms_scrapers_api
    newTag: v1.0.355

configMapGenerator:
  - name: sms-api-config
    behavior: merge
    envs:
      - config.env
