#!/usr/bin/env python3
"""Write .env for local dev from what is actually deployed.

Config comes from deploy/base/config.env plus the overlay's config.env (the
same files the cluster's ConfigMap is built from). Secrets come from the
environment's Secret in the cluster, which the Sealed Secrets controller has
already decrypted. Local settings (database, fake auth, no email) go on top.

    python deploy/dev-env.py              # dev secrets (the default)
    python deploy/dev-env.py --env prod   # prod secrets - real keys, be careful

Needs kubectl access to the cluster; KUBECONFIG defaults to
~/.kube/k3s-homelab.yaml. Re-run whenever a secret or config.env changes.
The previous .env is kept as .env.bak.
"""

import argparse
import base64
import json
import os
import subprocess
import sys
from pathlib import Path

from dotenv import dotenv_values

ROOT = Path(__file__).resolve().parent.parent
ENV_FILE = ROOT / ".env"

# What makes it local, on top of the deployed config.
LOCAL = {
    "DATABASE_URL": "postgresql+psycopg2://sms_user:localdev@localhost:5432/317_SMS",
    "POSTGRES_PASSWORD": "localdev",
    "EMAIL_DISABLED": "true",
    "DB_BACKUP_ENABLED": "false",
    "CORS_ALLOW_LOCALHOST": "true",
    "DEV_FAKE_AUTH": "1",
}
# An existing local database keeps working: these survive a re-run.
KEEP = ("DATABASE_URL", "POSTGRES_PASSWORD")


def quote(value: str) -> str:
    """Double-quoted, with the escapes python-dotenv and compose decode."""
    escaped = value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
    return f'"{escaped}"'


def cluster_secrets(namespace: str) -> dict[str, str]:
    env = {**os.environ}
    env.setdefault("KUBECONFIG", str(Path.home() / ".kube/k3s-homelab.yaml"))
    out = subprocess.run(
        ["kubectl", "-n", namespace, "get", "secret", "sms-api-secrets", "-o", "json"],
        capture_output=True, text=True, env=env, timeout=30,
    )
    if out.returncode != 0:
        sys.exit(f"couldn't read the secret from {namespace}: {out.stderr.strip()}")
    data = json.loads(out.stdout).get("data", {})
    return {k: base64.b64decode(v).decode() for k, v in data.items()}


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--env", choices=["dev", "prod"], default="dev")
    args = ap.parse_args()

    config = {
        **dotenv_values(ROOT / "deploy/base/config.env"),
        **dotenv_values(ROOT / f"deploy/overlays/{args.env}/config.env"),
    }
    secrets = cluster_secrets(f"sms-{args.env}")

    previous = dotenv_values(ENV_FILE) if ENV_FILE.exists() else {}
    local = {**LOCAL, **{k: previous[k] for k in KEEP if previous.get(k)}}

    merged = {**config, **secrets, **local}
    merged.pop("SCHEDULER_ENABLED", None)  # the prod cutover switch; locally, the default

    if ENV_FILE.exists():
        ENV_FILE.replace(ROOT / ".env.bak")
    lines = [f"# Generated by deploy/dev-env.py from sms-{args.env}. Don't edit - re-run it."]
    lines += [f"{k}={quote(v)}" for k, v in sorted(merged.items())]
    ENV_FILE.write_text("\n".join(lines) + "\n")
    ENV_FILE.chmod(0o600)
    print(f"wrote {ENV_FILE} ({len(config)} config, {len(secrets)} secrets from sms-{args.env})")


if __name__ == "__main__":
    main()
