"""add uploaded column

Revision ID: 44a52e3ee192
Revises: 
Create Date: 2026-03-16 11:39:46.597182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44a52e3ee192'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Assessment_Sheets', sa.Column('uploaded', sa.Boolean(), server_default='0', nullable=False))
    op.drop_column('Cadets', 'classification')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Cadets', sa.Column('classification', sa.TEXT(), nullable=True))
    op.drop_column('Assessment_Sheets', 'uploaded')
    # ### end Alembic commands ###
