"""add_parent_id_to_all_events

Revision ID: 37800a9c494f
Revises: f2a3b4c5d6e7
Create Date: 2026-04-17 17:32:17.204127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37800a9c494f'
down_revision: Union[str, Sequence[str], None] = 'f2a3b4c5d6e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('All_Events', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'All_Events', 'All_Events', ['parent_id'], ['id'], ondelete='CASCADE')
    op.drop_column('User_Profiles', 'no')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User_Profiles', sa.Column('no', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'All_Events', type_='foreignkey')
    op.drop_column('All_Events', 'parent_id')
    # ### end Alembic commands ###
